package controladores;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CCuidador.java
//  @ Date : 10/05/2024
//  @ Author : 
//
//


import modelos.Cuidador;
import modelos.interfaces.ICuidador;
import modelos.interfaces.IPropietario;
import persistentes.IPersistentesGenerica;
import persistentes.PCuidador;
import persistentes.PPropietario;
import vistas.VistaCuidado;
import vistas.VistaCuidador;

public class CCuidador extends CUsuario {
    private final VistaCuidador vistaCuidador;
    private final VistaCuidado vistaCuidado;

    public CCuidador() {
        super();
        this.vistaCuidador = new VistaCuidador();
        this.vistaCuidado = new VistaCuidado();
    }

    private String registrarCuidador(ICuidador newCuidador) {
        if (getLogeado() != null) {
            IPersistentesGenerica<ICuidador> persistencia = PCuidador.getInstance();
            if (persistencia.seleccionar(getLogeado())==null){
                persistencia.insertar(getLogeado(), newCuidador);
                return vistaCuidador.crearCuidador(newCuidador);
            } else {
                throw new RuntimeException();
            }
        } else throw new IllegalArgumentException("No estas logeado bby");
    }

    public String crear(String[] datos) {
        if (datos.length == 2) {
            ICuidador newCuidador = new Cuidador(getLogeado(), Double.parseDouble((datos[0])), datos[1]);
            return registrarCuidador(newCuidador);
        } else throw new RuntimeException("Datos insuficientes");
    }

    public void mostrarCuidados() {
        IPersistentesGenerica<ICuidador> persistencia = PCuidador.getInstance();
        ICuidador cuidador = persistencia.seleccionar(getLogeado());
        this.vistaCuidado.mostrarListadoCuidados(cuidador.getCuidados());

    }
    public boolean esCuidador() {
        IPersistentesGenerica<ICuidador> persistencia = PCuidador.getInstance();
        return persistencia.seleccionar(getLogeado())!=null;
    }
}
