package controladores;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CMascota.java
//  @ Date : 10/05/2024
//  @ Author : 
//
//


import modelos.Mascota;
import modelos.MascotaExotica;
import persistentes.IPersistentesGenerica;
import persistentes.PMascota;
import servidor.ExternalRIAC;
import vistas.VistaMascota;

public class CMascota {
    private final VistaMascota vista;

    public CMascota() {
        this.vista = new VistaMascota();
    }

    public void crearMascota(String[] datos) {
        if (datos.length == 8) {
            Mascota newMascota = new Mascota(datos[0], datos[1], Integer.parseInt(datos[2]), datos[3], datos[4], Integer.parseInt(datos[5]), datos[6], datos[7]);
            registrarMascota(newMascota);
        } else if (datos.length == 9) {
            MascotaExotica newMascotaExotica = new MascotaExotica(datos[0], datos[1], Integer.parseInt(datos[2]), datos[3], datos[4], Integer.parseInt(datos[5]), datos[6], datos[7], datos[8]);
            registrarMascotaExotica(newMascotaExotica);
        }


    }

    private void registrarMascota(Mascota mascota) {
        try {
            if (ExternalRIAC.RIAC(mascota.getRIAC())) {
                IPersistentesGenerica<Mascota> persistenciaMascota = PMascota.getInstance();
                persistenciaMascota.insertar(mascota.getRIAC(), mascota);
            } else {
                throw new RuntimeException();
            }
        } catch (RuntimeException e) {
        }
    }

    private void registrarMascotaExotica(MascotaExotica mascota) {
        try {
            if (ExternalRIAC.RIAC(mascota.getRIAC())) {
                IPersistentesGenerica<Mascota> persistenciaMascota = PMascota.getInstance();
                persistenciaMascota.insertar(mascota.getRIAC(), mascota);
            } else {
                throw new RuntimeException();
            }
        } catch (RuntimeException e) {
        }
    }

}
