package controladores;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CUsuario.java
//  @ Date : 10/05/2024
//  @ Author : 
//
//


import modelos.interfaces.ICuidador;
import modelos.interfaces.IPropietario;
import persistentes.IPersistentesGenerica;
import persistentes.PCuidador;
import persistentes.PPropietario;
import servidor.ExternalRRSS;


public class CUsuario {
    protected static String logeado;

    public CUsuario() {
    }

    public boolean login() {
        logeado = ExternalRRSS.LoginRRSS();
        boolean esCuidador;
        IPersistentesGenerica<IPropietario> persistencia1 = PPropietario.getInstance();
        IPersistentesGenerica<ICuidador> persistencia2 = PCuidador.getInstance();
        if(persistencia1.seleccionar(logeado)!=null){
            esCuidador = true;
        }else if(persistencia2.seleccionar(logeado)!=null){
            esCuidador = false;
        }else throw new IllegalArgumentException("El usuario no pertenece a la base de datos");
        return esCuidador;
    }
    public void loginFake() {
        logeado = ExternalRRSS.LoginRRSS();
    }



    public static String getLogeado() {
        return logeado;
    }
    public void setLogeado(String id){
        logeado = id;
    }

}
