package modelos;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cuidador.java
//  @ Date : 10/05/2024
//  @ Author : 
//
//


import modelos.interfaces.ICuidado;
import modelos.interfaces.ICuidador;

import java.util.List;

public class Cuidador extends Usuario implements ICuidador {
    public List<ICuidado> cuidados;
    private double tarifa;
    private String documentacion;

    public Cuidador(String id, double tarifa, String documentacion) {
        super(id);
        setTarifa(tarifa);
        setDocumentacion(documentacion);
    }
    @Override
    public List<ICuidado> getCuidados() {
        return this.cuidados;
    }

    @Override

    public double getTarifa() {
        return this.tarifa;
    }

    public void setTarifa(double tarifa) {
        if (tarifa <= 0)
            throw new IllegalArgumentException("La tarifa debe de ser mayor de 0");
        else this.tarifa = tarifa;
    }
    @Override
    public String getDocumentacion() {
        return this.documentacion;
    }

    public void setDocumentacion(String documentacion) {
        if (documentacion.isEmpty())
            throw new IllegalArgumentException("Se debe adjuntar una documentacion no vacía");
        else this.documentacion = documentacion;
    }

    @Override
    public String toString() {
        return "Cuidador{" +
                "tarifa=" + tarifa +
                ", documentacion='" + documentacion + '\'' +
                '}';
    }

}
