package modelos;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cuidado.java
//  @ Date : 10/05/2024
//  @ Author : 
//
//


import modelos.interfaces.ICuidado;
import persistentes.IPersistentesGenerica;
import persistentes.PCuidador;
import persistentes.PMascota;

import java.util.Date;

public class Cuidado implements ICuidado {
    private static int identificador = 1;
    private int id;
    private Date fechaFin;
    private Date fechaInic;
    private double tarifa;
    private Cuidador cuidador;
    private Mascota mascota;
    private IPersistentesGenerica pCuidador;
    private IPersistentesGenerica pMascota;

    public Cuidado(Date fechainicio, Date fechaFin, String cuidadorSSRR, String mascotaRIAC) {
        this.id = identificador++;
        this.fechaInic = fechainicio;
        this.fechaFin = fechaFin;
        this.pCuidador = PCuidador.getInstance();
        this.pMascota = PMascota.getInstance();
        try {
            this.cuidador = (Cuidador) pCuidador.seleccionar(cuidadorSSRR);
            System.out.println(this.cuidador.toString());
        } catch (Exception e) {
            System.err.println("Error seleccionando cuidador: " + cuidadorSSRR);
            e.printStackTrace();
        }
        this.tarifa = cuidador.getTarifa();
        try {
            this.mascota = (Mascota) pMascota.seleccionar(mascotaRIAC);
        } catch (Exception e) {
            System.err.println("Error seleccionando mascota: " + mascotaRIAC);
            e.printStackTrace();
        }
    }

    public Cuidado(Date fechaInicio, Date fechaFin) {
        this.id = identificador++;
        this.fechaInic = fechaInicio;
        this.fechaFin = fechaFin;
        this.tarifa = 0;
        this.cuidador = null;
        this.mascota = null;
    }

    public static int getIdentificador() {
        return identificador;
    }

    public static void setIdentificador(int identificador) {
        Cuidado.identificador = identificador;
    }

    public int getID() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Override
    public Date getFechaFin() {
        return fechaFin;
    }

    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    @Override
    public Date getFechaInic() {
        return fechaInic;
    }

    public void setFechaInic(Date fechaInic) {
        this.fechaInic = fechaInic;
    }

    public double getTarifa() {
        return tarifa;
    }

    public void setTarifa(double tarifa) {
        this.tarifa = tarifa;
    }

    @Override
    public Cuidador getCuidador() {
        return cuidador;
    }

    public void setCuidador(Cuidador cuidador) {
        this.cuidador = cuidador;
    }

    @Override
    public Mascota getMascota() {
        return mascota;
    }

    public void setMascota(Mascota mascota) {
        this.mascota = mascota;
    }
}
