package modelos;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Mascota_exotica.java
//  @ Date : 10/05/2024
//  @ Author : 
//
//


import java.io.File;

public class MascotaExotica extends Mascota {
    private String documentacionExtra;

    public MascotaExotica(String RIAC, String nombre, int edad, String raza, String especie, int numero_de_poliza, String ubicacion, String horario, String documentacionExtra) {
        super(RIAC, nombre, edad, raza, especie, numero_de_poliza, ubicacion, horario);
        this.setDocumentacionExtra(documentacionExtra);
    }

    public String getDocumentacionExtra() {
        return documentacionExtra;
    }

    private void setDocumentacionExtra(String documentacionExtra) {
        this.documentacionExtra = documentacionExtra;
    }

}
