package modelos;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Mascota.java
//  @ Date : 10/05/2024
//  @ Author : 
//
//


import modelos.interfaces.ICuidado;
import modelos.interfaces.IMascota;
import servidor.ExternalRIAC;

import java.util.HashMap;
import java.util.Map;

public class Mascota implements IMascota {
    public Map<String, ICuidado> Necesita;
    private String RIAC;
    private String nombre;
    private int edad;
    private String raza;
    private String especie;
    private int numero_de_poliza;
    private String ubicacion;
    private String horario;

    public Mascota(String RIAC, String nombre, int edad, String raza, String especie, int numeroDePoliza, String ubicacion, String horario) {
        setEdad(edad);
        setNombre(nombre);
        setRaza(raza);
        setEspecie(especie);
        setNumeroDePoliza(numeroDePoliza);
        setUbicacion(ubicacion);
        setHorario(horario);
        setRIAC(RIAC);
        this.Necesita = new HashMap<>();
    }

    public String getRIAC() {
        return RIAC;
    }

    private void setRIAC(String RIAC) {
        if (ExternalRIAC.RIAC(RIAC)) {
            this.RIAC = RIAC;
        } else throw new RuntimeException("Código RIAC inválido");
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        if (nombre == null)
            throw new IllegalArgumentException("Se debe introducir un nombre válido");
        else this.nombre = nombre;
    }

    public int getEdad() {
        return edad;
    }

    public void setEdad(int edad) {
        if (edad <= 0)
            throw new IllegalArgumentException("Se debe adjuntar una edad válida");
        else this.edad = edad;
    }

    public String getRaza() {
        return raza;
    }

    public void setRaza(String raza) {
        if (raza == null)
            throw new IllegalArgumentException("Se debe adjuntar una raza existente");
        else this.raza = raza;
    }

    public String getEspecie() {
        return especie;
    }

    public void setEspecie(String especie) {
        if (especie == null)
            throw new IllegalArgumentException("Se debe adjuntar una especie existente");
        else this.especie = especie;
    }

    public int getNumeroDePoliza() {
        return numero_de_poliza;
    }

    public void setNumeroDePoliza(int numero_de_poliza) {
        this.numero_de_poliza = numero_de_poliza;
    }

    public String getUbicacion() {
        return ubicacion;
    }

    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }

    public String getHorario() {
        return horario;
    }

    public void setHorario(String horario) {
        if (horario == null)
            throw new IllegalArgumentException("Se debe adjuntar un horario válido");
        else this.horario = horario;
    }

    public Map<String, ICuidado> getNecesita() {
        return Necesita;
    }

}
