package modelos;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Propietario.java
//  @ Date : 10/05/2024
//  @ Author : 
//
//


import modelos.interfaces.IMascota;
import modelos.interfaces.IPropietario;

import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

public class Propietario extends Usuario implements IPropietario {
    private Map<Integer, IMascota> lista_mascotas;

    public Propietario(String id) {
        super(id);
        this.lista_mascotas = new HashMap<>();
    }

    public Map<Integer, IMascota> getLista_mascotas() {
        return lista_mascotas;
    }

    public void setLista_mascotas(Map<Integer, IMascota> lista_mascotas) {
        this.lista_mascotas = lista_mascotas;
    }

    public void registrarMascota(Integer riac, Mascota mascota) {
        this.lista_mascotas.put(riac, mascota);
    }

    public List<IMascota> listarMascotas() {
        return new LinkedList<>(this.lista_mascotas.values());
    }
}
