package modelos;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Usuario.java
//  @ Date : 10/05/2024
//  @ Author : 
//
//

import modelos.interfaces.IUsuario;

public abstract class Usuario implements IUsuario {
    private String id;


    public Usuario(String id) {
        setId(id);
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        if (id.isEmpty())
            throw new IllegalArgumentException("ID no válido");
        else this.id = id;
    }
}
