package vistas;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VistaUsuario.java
//  @ Date : 10/05/2024
//  @ Author : 
//
//


import modelos.interfaces.IUsuario;

public class VistaUsuario {
    public VistaUsuario() {
    }

    public String register(IUsuario user) {
        System.out.println("Registro del usuario \"" + user.getId() + "\" exitoso");
        return "Registro del usuario \"" + user.getId() + "\" exitoso";
    }

    public String login(IUsuario user) {
        System.out.println("Login del usuario \"" + user.getId() + "\" exitoso");
        return "Login del usuario \"" + user.getId() + "\" exitoso";
    }

    public String logOut(IUsuario usuario) {
        System.out.println("Login exitoso del usuario: " + usuario.getId());
        return "Login exitoso del usuario: " + usuario.getId();
    }
}

