package vistas;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VistaMascota.java
//  @ Date : 10/05/2024
//  @ Author : 
//
//


import modelos.interfaces.IMascota;

import java.util.List;

public class VistaMascota {

    private static final String SEPARADOR = "___________________________________________";


    public VistaMascota() {
    }

    public String altaMascota(IMascota mascota) {
        System.out.println("Mascota \"" + mascota.getRIAC() + "\" dada de alta con exito");
        return "Mascota \"" + mascota.getRIAC() + "\" dada de alta con exito";
    }

    public String mostrarListado(List<IMascota> mascotas) {
        StringBuilder str = new StringBuilder("Mascotas a listar:" + "\n");
        for (IMascota mascota : mascotas) {
            str.append(SEPARADOR).append("\n");
            str.append("\t").append("RIAC: ");
            str.append(mascota.getRIAC()).append("\n");
            str.append("\t").append("Nombre: ");
            str.append(mascota.getNombre()).append("\n");
            str.append("\t").append("Tipo: ");
            str.append(mascota.getClass().getSimpleName()).append("\n");
        }
        str.append(SEPARADOR).append("\n");
        return str.toString();
    }

}
