package vistas;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VistaCuidador.java
//  @ Date : 10/05/2024
//  @ Author : 
//
//


import modelos.interfaces.ICuidador;

public class VistaCuidador {
    public String crearCuidador(ICuidador cuidador) {
        System.out.println("Cuidador \"" + cuidador.getId() + "\" creado con exito: ");
        return "Cuidador \"" + cuidador.getId() + "\" creado con exito: ";
    }


}
