package persistentes;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PMascota_exotica.java
//  @ Date : 10/05/2024
//  @ Author : 
//
//


import modelos.MascotaExotica;

import java.io.*;
import java.util.HashMap;

public class PMascota_exotica implements IPersistentesGenerica<MascotaExotica> {

    private static PMascota_exotica instance;
    private final HashMap<String, MascotaExotica> mascotaExoticas;

    private PMascota_exotica() {
        this.mascotaExoticas = new HashMap<>();
    }

    public static PMascota_exotica getInstance() {
        if (instance == null) instance = new PMascota_exotica();
        return instance;
    }

    public void pasarFicherosAListas() {
        leerMascotasExoticas(this.mascotaExoticas);
    }

    private void leerMascotasExoticas(HashMap<String, MascotaExotica> lista) {
        try (BufferedReader lector = new BufferedReader(new FileReader("docs\\persistencias\\Mascota_exotica.txt"))) {
            String linea;
            while ((linea = lector.readLine()) != null) {
                String[] bloques = linea.split("_");
                if (bloques.length < 9) {
                    System.err.println("Línea mal formada: " + linea);
                    continue;
                }
                try {
                    String RIAC = bloques[0];
                    String nombre = bloques[1];
                    int edad = Integer.parseInt(bloques[2]);
                    String raza = bloques[3];
                    String especie = bloques[4];
                    int numero_de_poliza = Integer.parseInt(bloques[5]);
                    String ubicacion = bloques[6];
                    String horario = bloques[7];
                    String documentacionExtra = bloques[8];
                    lista.put(RIAC, new MascotaExotica(RIAC, nombre, edad, raza, especie, numero_de_poliza, ubicacion, horario, documentacionExtra));
                } catch (Exception e) {
                    System.err.println("Error procesando la línea: " + linea);
                }
            }
        } catch (IOException e) {
            System.out.println("Error al leer el archivo: " + e.getMessage());
        }
    }

    @Override
    public void insertar(String RIAC, MascotaExotica mascotaExotica) {
        try {
            BufferedWriter escritor = new BufferedWriter(new FileWriter("docs\\persistencias\\Mascota_exotica.txt", true));
            escritor.write(mascotaExotica.getRIAC() + "_" + mascotaExotica.getNombre() + "_" + mascotaExotica.getEdad() + "_" + mascotaExotica.getRaza() + "_" + mascotaExotica.getEspecie() + "_" + mascotaExotica.getNumeroDePoliza() + "_" + mascotaExotica.getUbicacion() + "_" + mascotaExotica.getHorario() + "_" + mascotaExotica.getDocumentacionExtra());
            escritor.newLine();
            escritor.close();
            this.mascotaExoticas.put(RIAC, new MascotaExotica(mascotaExotica.getRIAC(), mascotaExotica.getNombre(),mascotaExotica.getEdad(),mascotaExotica.getRaza(), mascotaExotica.getEspecie() ,mascotaExotica.getNumeroDePoliza() ,mascotaExotica.getUbicacion() , mascotaExotica.getHorario() ,mascotaExotica.getDocumentacionExtra()));
        } catch (IOException e) {
            System.out.println("Error al leer el archivo: " + e.getMessage());
        }
    }

    @Override
    public MascotaExotica seleccionar(String RIAC) {
        if (this.mascotaExoticas.containsKey(RIAC)) {
            return this.mascotaExoticas.get(RIAC);
        }
        else return null;
    }

    @Override
    public void actualizar() {

    }

    @Override
    public void borrar(String RIAC) {

    }

}
