package persistentes;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PMascota.java
//  @ Date : 10/05/2024
//  @ Author : 
//
//


import modelos.Mascota;

import java.io.*;
import java.util.HashMap;

public class PMascota implements IPersistentesGenerica<Mascota> {
    private static PMascota instance;
    private final HashMap<String, Mascota> mascotas;

    private PMascota() {
        this.mascotas = new HashMap<>();
    }

    public static PMascota getInstance() {
        if (instance == null) instance = new PMascota();
        return instance;
    }

    public void pasarFicherosAListas() {
        leerMascotas(this.mascotas);
    }

    private void leerMascotas(HashMap<String, Mascota> lista) {
        try (BufferedReader lector = new BufferedReader(new FileReader("docs\\persistencias\\Mascota.txt"))) {
            String linea;
            while ((linea = lector.readLine()) != null) {
                String[] bloques = linea.split("_");
                if (bloques.length < 8) {
                    System.err.println("Línea mal formada: " + linea);
                    continue;
                }
                try {
                    String RIAC = bloques[0];
                    String nombre = bloques[1];
                    int edad = Integer.parseInt(bloques[2]);
                    String raza = bloques[3];
                    String especie = bloques[4];
                    int numero_de_poliza = Integer.parseInt(bloques[5]);
                    String ubicacion = bloques[6];
                    String horario = bloques[7];
                    lista.put(RIAC, new Mascota(RIAC, nombre, edad, raza, especie, numero_de_poliza, ubicacion, horario));
                } catch (Exception e) {
                    System.err.println("Error procesando la línea: " + linea);
                }
            }
        } catch (IOException e) {
            System.out.println("Error al leer el archivo: " + e.getMessage());
        }
    }

    @Override
    public void insertar(String RIAC, Mascota mascota) {
        try {
            BufferedWriter escritor = new BufferedWriter(new FileWriter("docs\\persistencias\\Mascota.txt", true));
            escritor.write(mascota.getRIAC() + "_" + mascota.getNombre() + "_" + mascota.getEdad() + "_" + mascota.getRaza() + "_" + mascota.getEspecie() + "_" + mascota.getNumeroDePoliza() + "_" + mascota.getUbicacion() + "_" + mascota.getHorario());
            escritor.newLine();
            escritor.close();
            this.mascotas.put(RIAC, new Mascota(RIAC, mascota.getNombre(), mascota.getEdad(), mascota.getRaza(), mascota.getEspecie(), mascota.getNumeroDePoliza(), mascota.getUbicacion(), mascota.getHorario()));
        } catch (IOException e) {
            System.out.println("Error al leer el archivo: " + e.getMessage());
        }
    }

    @Override
    public Mascota seleccionar(String RIAC) {
        if (this.mascotas.containsKey(RIAC)) {
            return this.mascotas.get(RIAC);
        }
        else return null;
    }

    @Override
    public void actualizar() {
        // Implementar la lógica de actualización aquí
    }

    @Override
    public void borrar(String RIAC) {
        // Implementar la lógica de borrado aquí
    }
}
