package persistentes;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PUsuario.java
//  @ Date : 10/05/2024
//  @ Author : 
//
//


import modelos.Propietario;
import modelos.interfaces.IPropietario;

import java.io.*;
import java.util.HashMap;

public class PPropietario implements IPersistentesGenerica<IPropietario> {
    private static PPropietario instance;
    private final HashMap<String, IPropietario> propietarios;

    private PPropietario() {
        this.propietarios = new HashMap<>();
    }

    public static PPropietario getInstance() {
        if (instance == null) instance = new PPropietario();
        return instance;
    }

    private void leerPropietarios(HashMap<String, IPropietario> lista) {
        try (BufferedReader lector = new BufferedReader(new FileReader("docs\\persistencias\\Propietario.txt"))) {
            String linea;
            while ((linea = lector.readLine()) != null) {
                String[] bloques = linea.split("_");
                if (bloques.length < 1) {
                    System.err.println("Línea mal formada: " + linea);
                    continue;
                }
                try {
                    String ide = bloques[0];
                    lista.put(ide, new Propietario(ide));
                } catch (Exception e) {
                    System.err.println("Error procesando la línea: " + linea);
                }
            }
        } catch (IOException e) {
            System.out.println("Error al leer el archivo: " + e.getMessage());
        }
    }

    @Override
    public void insertar(String ssrr, IPropietario propietario) {
        try {
            BufferedWriter escritor = new BufferedWriter(new FileWriter("docs\\persistencias\\Propietario.txt", true));
            escritor.write(ssrr);
            escritor.newLine();
            escritor.close();
            this.propietarios.put(ssrr, new Propietario(ssrr));
        } catch (IOException e) {
            System.out.println("Error al leer el archivo: " + e.getMessage());
        }
    }

    @Override
    public IPropietario seleccionar(String clave) {
        if (this.propietarios.containsKey(clave)) {
            return this.propietarios.get(clave);
        }
        else return null;
    }

    @Override
    public void actualizar() {

    }

    @Override
    public void borrar(String clave) {

    }

    @Override
    public void pasarFicherosAListas() {
        leerPropietarios(this.propietarios);
    }
}
