package modelos.interfaces;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ICuidador.java
//  @ Date : 10/05/2024
//  @ Author : 
//
//


import modelos.Cuidador;

import java.util.List;

public interface ICuidador extends IUsuario {
    List<ICuidado> getCuidados();
    double getTarifa();
    String getDocumentacion();
}
