package modelos.interfaces;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IMascota.java
//  @ Date : 10/05/2024
//  @ Author : 
//
//


public interface IMascota {
    String getRIAC();

    String getNombre();
}
